/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(alarm)'}/alarm` | `/alarm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(group)'}/group` | `/group`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/services/auth`; params?: Router.UnknownInputParams; } | { pathname: `/services/group`; params?: Router.UnknownInputParams; } | { pathname: `/services/http`; params?: Router.UnknownInputParams; } | { pathname: `/services/jwt`; params?: Router.UnknownInputParams; } | { pathname: `/services/storage`; params?: Router.UnknownInputParams; } | { pathname: `/services/user`; params?: Router.UnknownInputParams; } | { pathname: `/storageScreen/DebugStorageModal`; params?: Router.UnknownInputParams; } | { pathname: `/storageScreen/useAsyncStorageDump`; params?: Router.UnknownInputParams; } | { pathname: `/types/groups`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(alarm)'}/alarm` | `/alarm`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(group)'}/group` | `/group`; params?: Router.UnknownOutputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/services/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/services/group`; params?: Router.UnknownOutputParams; } | { pathname: `/services/http`; params?: Router.UnknownOutputParams; } | { pathname: `/services/jwt`; params?: Router.UnknownOutputParams; } | { pathname: `/services/storage`; params?: Router.UnknownOutputParams; } | { pathname: `/services/user`; params?: Router.UnknownOutputParams; } | { pathname: `/storageScreen/DebugStorageModal`; params?: Router.UnknownOutputParams; } | { pathname: `/storageScreen/useAsyncStorageDump`; params?: Router.UnknownOutputParams; } | { pathname: `/types/groups`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(alarm)'}/alarm${`?${string}` | `#${string}` | ''}` | `/alarm${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Register${`?${string}` | `#${string}` | ''}` | `/Register${`?${string}` | `#${string}` | ''}` | `${'/(group)'}/group${`?${string}` | `#${string}` | ''}` | `/group${`?${string}` | `#${string}` | ''}` | `/context/AuthContext${`?${string}` | `#${string}` | ''}` | `/services/auth${`?${string}` | `#${string}` | ''}` | `/services/group${`?${string}` | `#${string}` | ''}` | `/services/http${`?${string}` | `#${string}` | ''}` | `/services/jwt${`?${string}` | `#${string}` | ''}` | `/services/storage${`?${string}` | `#${string}` | ''}` | `/services/user${`?${string}` | `#${string}` | ''}` | `/storageScreen/DebugStorageModal${`?${string}` | `#${string}` | ''}` | `/storageScreen/useAsyncStorageDump${`?${string}` | `#${string}` | ''}` | `/types/groups${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(alarm)'}/alarm` | `/alarm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(group)'}/group` | `/group`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/services/auth`; params?: Router.UnknownInputParams; } | { pathname: `/services/group`; params?: Router.UnknownInputParams; } | { pathname: `/services/http`; params?: Router.UnknownInputParams; } | { pathname: `/services/jwt`; params?: Router.UnknownInputParams; } | { pathname: `/services/storage`; params?: Router.UnknownInputParams; } | { pathname: `/services/user`; params?: Router.UnknownInputParams; } | { pathname: `/storageScreen/DebugStorageModal`; params?: Router.UnknownInputParams; } | { pathname: `/storageScreen/useAsyncStorageDump`; params?: Router.UnknownInputParams; } | { pathname: `/types/groups`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
