spring:
  application:
    name: yourmeds

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/yourmeds_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago}
    #url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always