services:
  db:
    image: mysql:8.0
    container_name: yourmeds-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: yourmeds_db
      MYSQL_USER: yourmeds_user
      MYSQL_PASSWORD: yourmeds_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: yourmeds-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/yourmeds_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago
      SPRING_DATASOURCE_USERNAME: yourmeds_user
      SPRING_DATASOURCE_PASSWORD: yourmeds_pass

    ports:
      - "8080:8080"

volumes:
  db_data:
